import type { Question } from '../types';

export const quizQuestions: Question[] = [
  // USE OF ENGLISH
  {
    id: 1,
    subject: 'USE OF ENGLISH',
    question: 'The solution to the problem is, happily, _________',
    options: {
      A: 'at hand',
      B: 'on hand',
      C: 'within hand',
      D: 'near hand',
    },
    correctAnswer: 'A',
  },
  {
    id: 2,
    subject: 'USE OF ENGLISH',
    question: 'My grandmother told a story that made me_____',
    options: {
      A: 'laughing',
      B: 'laugh',
      C: 'laughed',
      D: 'to laugh',
    },
    correctAnswer: 'B',
  },
  {
    id: 3,
    subject: 'USE OF ENGLISH',
    question: 'The principal, with all the teachers and students ___',
    options: {
      A: 'has arrived',
      B: 'were arriving',
      C: 'have arrived',
      D: 'were to arrive',
    },
    correctAnswer: 'A',
  },
  {
    id: 4,
    subject: 'USE OF ENGLISH',
    question: 'The triplets love _____very much.',
    options: {
      A: 'each other',
      B: 'one another',
      C: 'the other',
      D: 'the others',
    },
    correctAnswer: 'A',
  },
  {
    id: 5,
    subject: 'USE OF ENGLISH',
    question: 'The man asked if she ____her race.',
    options: {
      A: 'have run',
      B: 'had ran',
      C: 'have ran',
      D: 'had run',
    },
    correctAnswer: 'D',
  },
  {
    id: 6,
    subject: 'USE OF ENGLISH',
    question: 'Please ____the light before you sleep.',
    options: {
      A: 'extinguish',
      B: 'put out',
      C: 'put off',
      D: 'switch off',
    },
    correctAnswer: 'B',
  },
  {
    id: 7,
    subject: 'USE OF ENGLISH',
    question: 'The woman ______________ the sharp knife from the baby in a subtle way.',
    options: {
      A: 'wrested',
      B: 'rested',
      C: 'wrestled',
      D: 'arrested',
    },
    correctAnswer: 'A',
  },
  {
    id: 8,
    subject: 'USE OF ENGLISH',
    question: 'The elders felt it was a forlorn hope and vehemently opposed it.',
    options: {
      A: 'a dangerous plan',
      B: 'a plan which would not favour the elders',
      C: 'a planless course of action.',
      D: 'a plan which had very little likelihood of success.',
    },
    correctAnswer: 'D',
  },
  {
    id: 9,
    subject: 'USE OF ENGLISH',
    question: 'Bisi stole a march on us by beating the gun at the race.',
    options: {
      A: 'gained an advantage',
      B: 'came last',
      C: 'came first',
      D: 'was disqualified',
    },
    correctAnswer: 'A',
  },
  {
    id: 10,
    subject: 'USE OF ENGLISH',
    question: 'The rioters despoiled the main markets.',
    options: {
      A: 'looted',
      B: 'destroyed',
      C: 'burnt',
      D: 'desecrated',
    },
    correctAnswer: 'A',
  },
  // PHYSICS
  {
    id: 11,
    subject: 'PHYSICS',
    question: 'Which of the following is not a general characteristic of waves?',
    options: {
      A: 'Diffraction',
      B: 'Polarization',
      C: 'Reflection',
      D: 'Refraction',
    },
    correctAnswer: 'B',
  },
  {
    id: 12,
    subject: 'PHYSICS',
    question: 'What type of electromagnetic radiation can be used to take photographs in the haze?',
    options: {
      A: 'Radio waves',
      B: 'Visible rays',
      C: 'Ultraviolet rays',
      D: 'Infrared rays',
    },
    correctAnswer: 'D',
  },
  {
    id: 13,
    subject: 'PHYSICS',
    question: 'A man hears his echo from a nearby hill 2 seconds after he shouted. If the frequency of his voice is 260Hz and the wavelength is 1.20m, how far away is the hill?',
    options: {
      A: '312m',
      B: '315m',
      C: '335m',
      D: '340m',
    },
    correctAnswer: 'A',
  },
  {
    id: 14,
    subject: 'PHYSICS',
    question: 'Find the potential energy of a diver of mass 75kg at a height of 10m above a swimming pool (acceleration due to gravity = 9.8ms-2).',
    options: {
      A: '7.35KJ',
      B: '9.41KJ',
      C: '8.82KJ',
      D: '0.75KJ',
    },
    correctAnswer: 'A',
  },
  {
    id: 15,
    subject: 'PHYSICS',
    question: 'Find the combined resistance of two wires each of resistance 8-ohms when they are connected in parallel.',
    options: {
      A: '16-ohms',
      B: '4-ohms',
      C: '20-ohms',
      D: '12-ohms',
    },
    correctAnswer: 'B',
  },
  {
    id: 16,
    subject: 'PHYSICS',
    question: 'A load of 5N gives an extension of 0.56cm in a wire which obeys Hook’s Law. What is the extension caused by a load of 20N?',
    options: {
      A: '2.14cm',
      B: '2.24cm',
      C: '1.12cm',
      D: '2.52cm',
    },
    correctAnswer: 'B',
  },
  {
    id: 17,
    subject: 'PHYSICS',
    question: 'A cube of side 20cm floats in water with 15cm of its height submerged. What is the density of the material of the cube?',
    options: {
      A: '1.85gcm-3',
      B: '0.85gcm-3',
      C: '0.75gcm-3',
      D: '0.65gcm-3',
    },
    correctAnswer: 'C',
  },
  {
    id: 18,
    subject: 'PHYSICS',
    question: 'Hot water is added to four times its mass of water at 20°C and the resulting temperature is 30°C. What is the initial temperature of the hot water? (assume constant specific heat capacity)',
    options: {
      A: '50°C',
      B: '60°C',
      C: '70°C',
      D: '80°C',
    },
    correctAnswer: 'C',
  },
  {
    id: 19,
    subject: 'PHYSICS',
    question: 'What happens to the proton number Z and the nucleon number A of a nuclide which emits a y-radiation?',
    options: {
      A: 'Z increases by 1 while A does not change',
      B: 'Z increases by 1 and A increases by 1',
      C: 'Z and A neither increase or decrease',
      D: 'Z increases by 1 while A decreases by 1',
    },
    correctAnswer: 'C',
  },
  {
    id: 20,
    subject: 'PHYSICS',
    question: 'A siren having a ring of 200 holes makes 132 revolutions per minute. A jet of air is directed on the set of holes. Calculate the frequency of the note produced. (Take the speed of sound in air as 350m/s)',
    options: {
      A: '26.40Hz',
      B: '1.52Hz',
      C: '440Hz',
      D: '0.66Hz',
    },
    correctAnswer: 'C',
  },
  // CHEMISTRY
  {
    id: 21,
    subject: 'CHEMISTRY',
    question: 'A mixture of 0.20 mole of Ar, 0.20mole of Na and 0.30 mole of He exerts a total pressure of 2.1 atmosphere. What is the partial pressure of He in the mixture.',
    options: {
      A: '0.70 atmosphere',
      B: '0.80 atmosphere',
      C: '0.90 atmosphere',
      D: '0.65 atmosphere',
    },
    correctAnswer: 'C',
  },
  {
    id: 22,
    subject: 'CHEMISTRY',
    question: 'White phosphorus is stored under water because it _____',
    options: {
      A: 'is corrosive',
      B: 'has a low ignition temperature',
      C: 'reacts with carbon (IV) oxide',
      D: 'is hydrolyzed by atmospheric moisture',
    },
    correctAnswer: 'B',
  },
  {
    id: 23,
    subject: 'CHEMISTRY',
    question: 'What is the general formula of carbohydrates?',
    options: {
      A: 'CnH2nOn',
      B: 'Cx(H2O)y',
      C: 'C6H10O5',
      D: 'C6H12O6',
    },
    correctAnswer: 'B',
  },
  {
    id: 24,
    subject: 'CHEMISTRY',
    question: 'Isotopy is due to differences in the number of _____',
    options: {
      A: 'atomic mass',
      B: 'molecular mass',
      C: 'protons',
      D: 'neutrons',
    },
    correctAnswer: 'D',
  },
  {
    id: 25,
    subject: 'CHEMISTRY',
    question: 'If the pH of a solution of dilute hydrochloric acid is given as 2. The concentration of this solution in mol dm-3 is _____',
    options: {
      A: '0.01',
      B: '0.02',
      C: '1.0',
      D: '2.0',
    },
    correctAnswer: 'A',
  },
  {
    id: 26,
    subject: 'CHEMISTRY',
    question: 'Aluminium materials should not be exposed to alkalis because aluminium is _____',
    options: {
      A: 'basic',
      B: 'acidic',
      C: 'amphoteric',
      D: 'a reducing agent',
    },
    correctAnswer: 'C',
  },
  {
    id: 27,
    subject: 'CHEMISTRY',
    question: 'When K2Cr2O7 dissolves in water, the following equilibrium is established: Cr2O7^2-(aq) + H2O(l) <=> 2CrO4^2-(aq) + 2H+(aq) Orange yellow State the colour observed on adding a few drops of dilute H2SO4 in the system.',
    options: {
      A: 'orange',
      B: 'yellow',
      C: 'pink',
      D: 'colourless',
    },
    correctAnswer: 'A',
  },
  {
    id: 28,
    subject: 'CHEMISTRY',
    question: 'The percentage by volume of nitrogen in air is high because _____',
    options: {
      A: 'Nitrogen is relatively inactive',
      B: 'Nitrogen supports life',
      C: 'Nitrogen prevents corrosion of metals',
      D: 'Nitrogen increases the rate of combustion',
    },
    correctAnswer: 'A',
  },
  {
    id: 29,
    subject: 'CHEMISTRY',
    question: 'Which of the following is not a mixture?',
    options: {
      A: 'sea water',
      B: 'Iron II sulphide',
      C: 'Petroleum',
      D: 'Urine',
    },
    correctAnswer: 'B',
  },
  {
    id: 30,
    subject: 'CHEMISTRY',
    question: 'Sodium chloride may be obtained from brine by _____',
    options: {
      A: 'Decantation',
      B: 'Distillation',
      C: 'Evaporation',
      D: 'Sublimation',
    },
    correctAnswer: 'C',
  },
  // BIOLOGY
  {
    id: 31,
    subject: 'BIOLOGY',
    question: 'When two genes for the same character (alleles) are contained in the same individual. The character that shows is known as _____',
    options: {
      A: 'Important character',
      B: 'Dominant character',
      C: 'Superior character',
      D: 'Controlling character',
    },
    correctAnswer: 'B',
  },
  {
    id: 32,
    subject: 'BIOLOGY',
    question: 'Which of the following is not present in the nucleus of cell?',
    options: {
      A: 'Chromosome',
      B: 'Nucleolus',
      C: 'Genes',
      D: 'Mitochondria',
    },
    correctAnswer: 'D',
  },
  {
    id: 33,
    subject: 'BIOLOGY',
    question: 'What force is responsible for the movement of water to the top of tall trees?',
    options: {
      A: 'Transpiration pull',
      B: 'Root pressure',
      C: 'Diffusion',
      D: 'Capillary pressure',
    },
    correctAnswer: 'A',
  },
  {
    id: 34,
    subject: 'BIOLOGY',
    question: 'Which of the following is the largest single cell in the body?',
    options: {
      A: 'the neuron',
      B: 'the ovum',
      C: 'liver cell',
      D: 'muscle cell',
    },
    correctAnswer: 'B',
  },
  {
    id: 35,
    subject: 'BIOLOGY',
    question: 'Which of the following is not a function of the liver?',
    options: {
      A: 'storage of iron',
      B: 'formation of bile',
      C: 'breakdown of excess amino acid',
      D: 'excretion of urine from the blood',
    },
    correctAnswer: 'D',
  },
  {
    id: 36,
    subject: 'BIOLOGY',
    question: 'Hydra is able to perform all the following except _____',
    options: {
      A: 'feeding',
      B: 'photosynthesis',
      C: 'moving',
      D: 'egestion',
    },
    correctAnswer: 'B',
  },
  {
    id: 37,
    subject: 'BIOLOGY',
    question: 'The maintenance of a constant internal environment is called _____',
    options: {
      A: 'environmental regulation',
      B: 'balance in nature',
      C: 'peristalsis',
      D: 'homeostasis',
    },
    correctAnswer: 'D',
  },
  {
    id: 38,
    subject: 'BIOLOGY',
    question: 'Autotrophs are also describes as _____',
    options: {
      A: 'Consumers',
      B: 'Carnivores',
      C: 'Producers',
      D: 'Decomposers',
    },
    correctAnswer: 'C',
  },
  {
    id: 39,
    subject: 'BIOLOGY',
    question: 'Insects which undergo complete metamorphosis are those that _____',
    options: {
      A: 'have the four distinct stages in their life cycle',
      B: 'do not have the larval stage',
      C: 'have larva and pupa which resemble the adult',
      D: 'their eggs hatch to produce nymphs',
    },
    correctAnswer: 'A',
  },
  {
    id: 40,
    subject: 'BIOLOGY',
    question: 'Nervous control differs from hormonal control in that the former _____',
    options: {
      A: 'is a slower process',
      B: 'involves only chemical reaction',
      C: 'produce short-term changes',
      D: 'has no specific pathway',
    },
    correctAnswer: 'C',
  },
];
