
import type { Question } from '../types';

export const quizQuestions: Question[] = [
  // USE OF ENGLISH
  {
    id: 1,
    subject: 'USE OF ENGLISH',
    question: 'The most important aspect of agriculture mentioned in the passage is',
    options: {
      A: 'Poultry',
      B: 'Fishery',
      C: 'Livestock',
      D: 'Farming',
    },
    correctAnswer: 'D',
  },
  {
    id: 2,
    subject: 'USE OF ENGLISH',
    question: 'Farming in many countries today is',
    options: {
      A: 'an alternative to poultry',
      B: 'of great assistance to the economy',
      C: 'for those who are out of job',
      D: 'for the illiterates',
    },
    correctAnswer: 'B',
  },
  {
    id: 3,
    subject: 'USE OF ENGLISH',
    question: 'Some countries produce more and better crops than others because the farmers in the former',
    options: {
      A: 'are more educated',
      B: 'have greater manpower',
      C: 'have more modern equipment',
      D: 'have more fertile land',
    },
    correctAnswer: 'C',
  },
  {
    id: 4,
    subject: 'USE OF ENGLISH',
    question: 'In order to help improve the state of farming, the Government should',
    options: {
      A: 'give all farmers enough money to work with',
      B: 'Sell enough fertilizers to all farmers',
      C: 'find ways of financing and modernizing the farming system',
      D: 'help farmers with the storage of their crops',
    },
    correctAnswer: 'C',
  },
  {
    id: 5,
    subject: 'USE OF ENGLISH',
    question: 'A lot of crops harvested are wasted because farmers',
    options: {
      A: 'allow insects and pests to destroy their crops',
      B: 'do not have enough money to invest in harvesters',
      C: 'do not have storage facilities',
      D: 'harvest too much at a time',
    },
    correctAnswer: 'C',
  },
  {
    id: 6,
    subject: 'USE OF ENGLISH',
    question: 'The author believes that electronic recording is',
    options: {
      A: 'superior only to mental recording',
      B: 'inferior to both mental recording and writing',
      C: 'superior to both mental recording and writing',
      D: 'inferior to only writing',
    },
    correctAnswer: 'C',
  },
  {
    id: 7,
    subject: 'USE OF ENGLISH',
    question: 'The writer believes that the art of record keeping has',
    options: {
      A: 'improved over the years',
      B: 'endangered the art of writing',
      C: 'changed human memory',
      D: 'overcome all the problems facing human',
    },
    correctAnswer: 'A',
  },
  {
    id: 8,
    subject: 'USE OF ENGLISH',
    question: 'How many stages of development did the writer mention while discussing the art of record keeping?',
    options: { A: 'Two', B: 'Three', C: 'Four', D: 'Five' },
    correctAnswer: 'B',
  },
  {
    id: 9,
    subject: 'USE OF ENGLISH',
    question: 'According to the author, human memory is unreliable because people',
    options: {
      A: 'die and we forget what they said',
      B: 'forget events or tell lies',
      C: 'do not always know when events happen',
      D: 'do not always know who did what and when',
    },
    correctAnswer: 'B',
  },
  {
    id: 10,
    subject: 'USE OF ENGLISH',
    question: 'From the passage, we gather that writing is almost',
    options: {
      A: 'as unreliable as human memory',
      B: 'as reliable as electronic memory',
      C: 'more reliable than electronic memory',
      D: 'not to be compared to any other recording system',
    },
    correctAnswer: 'A',
  },
  {
    id: 11,
    subject: 'USE OF ENGLISH',
    question: 'Identify the option that has a STRESS PATTERN different from the rest:',
    options: { A: 'Factory', B: 'Distinctive', C: 'Regular', D: 'National' },
    correctAnswer: 'B',
  },
  {
    id: 12,
    subject: 'USE OF ENGLISH',
    question: 'Identify the option that has a STRESS PATTERN different from the rest:',
    options: { A: 'Interpret', B: 'Period', C: 'Destructive', D: 'Forever' },
    correctAnswer: 'C',
  },
  {
    id: 13,
    subject: 'USE OF ENGLISH',
    question: 'Identify the option that has a STRESS PATTERN different from the rest:',
    options: { A: 'Unless', B: 'Enact', C: 'Useless', D: 'Combine' },
    correctAnswer: 'C',
  },
  {
    id: 14,
    subject: 'USE OF ENGLISH',
    question: "Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: The singer's popularity is beginning to decline.",
    options: { A: 'slope', B: 'disappear', C: 'wane', D: 'darken' },
    correctAnswer: 'C',
  },
  {
    id: 15,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: Ade is at the verge of nervous breakdown, so he must be very careful.',
    options: { A: 'brink', B: 'margin', C: 'avenue', D: 'fringe' },
    correctAnswer: 'A',
  },
  {
    id: 16,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: An open car gives no protection against the elements.',
    options: { A: 'weather', B: 'atoms', C: 'dust', D: 'atmosphere' },
    correctAnswer: 'A',
  },
  {
    id: 17,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: He has never been a good mediator even in minor family disputes because, in most cases his views are jaundiced.',
    options: { A: 'coloured', B: 'prejudiced', C: 'suspicious', D: 'unscrupulous' },
    correctAnswer: 'B',
  },
  {
    id: 18,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: In some parts of our society, people are ostracized purely on the basis of their parentage.',
    options: {
      A: 'hated',
      B: 'disrespected',
      C: 'locked up',
      D: 'shut off from others',
    },
    correctAnswer: 'D',
  },
  {
    id: 19,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: My friend will hate his uncle forever because he left him in the lurch at his hour of need.',
    options: {
      A: 'abandoned him',
      B: 'punished',
      C: 'disrespected him',
      D: 'despised him',
    },
    correctAnswer: 'A',
  },
  {
    id: 20,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: All the efforts made to settle the quarrel were futile',
    options: { A: 'successful', B: 'fruitless', C: 'wicked', D: 'reasonable' },
    correctAnswer: 'B',
  },
  {
    id: 21,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: Kelechi hardly ever falls sick',
    options: { A: 'most often', B: 'very seldom', C: 'frequently', D: 'sometimes' },
    correctAnswer: 'B',
  },
  {
    id: 22,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: It is sheer fantasy to believe that there could never be a miscalculation by any nation that has atomic weapon',
    options: { A: 'dream', B: 'hope', C: 'nonsense', D: 'joke' },
    correctAnswer: 'A',
  },
  {
    id: 23,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: The ingenious scheme of the robber broke down because of the efficiency of the police officer.',
    options: { A: 'suspicious', B: 'ambitious', C: 'deceitful', D: 'clever' },
    correctAnswer: 'D',
  },
  {
    id: 24,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: Our town is so small that we are always meeting our school master accidentally',
    options: { A: 'falling into', B: 'finding', C: 'running into', D: 'stepping on' },
    correctAnswer: 'C',
  },
  {
    id: 25,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: One has to score not less than 200 marks in the UME together with meeting other conditions to be qualified to write the Uniben post UME screening test.',
    options: {
      A: 'to be exempted',
      B: 'to become a candidate for',
      C: 'to be considered',
      D: 'to seek permission for',
    },
    correctAnswer: 'B',
  },
  {
    id: 26,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option NEAREST IN MEANING to the word(s) or phrase(s) underlined: He went through fire before he qualified as a doctor',
    options: {
      A: 'a fire accident',
      B: 'a hilarious experience',
      C: 'some purification',
      D: 'some "tough" time',
    },
    correctAnswer: 'D',
  },
  {
    id: 27,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: The chairman\'s verdict redressed the injustice meted out by the secretary',
    options: { A: 'corrected', B: 'restored', C: 'aggravated', D: 'addressed' },
    correctAnswer: 'C',
  },
  {
    id: 28,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Uche could not travel last December because of the severity of the harmattan',
    options: { A: 'cold', B: 'mildness', C: 'warmth', D: 'moderation' },
    correctAnswer: 'B',
  },
  {
    id: 29,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Travelling in the night can be an ordeal',
    options: {
      A: 'a great exercise',
      B: 'a great fear',
      C: 'a great endurance',
      D: 'a great pleasure',
    },
    correctAnswer: 'D',
  },
  {
    id: 30,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Bola is very provocative in her style of dressing,',
    options: { A: 'modest', B: 'happy', C: 'angry', D: 'beautiful' },
    correctAnswer: 'A',
  },
  {
    id: 31,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Joke thought that her father was very callous',
    options: { A: 'indifferent', B: 'compassionate', C: 'wicked', D: 'careless' },
    correctAnswer: 'B',
  },
  {
    id: 32,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: "The Lions" of Cameroun is really an indomitable team',
    options: {
      A: 'a powerful',
      B: 'a compassionate',
      C: 'a weak',
      D: 'an unyielding team',
    },
    correctAnswer: 'C',
  },
  {
    id: 33,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: To almost everyone in the little village, Ada\'s behaviour was almost odious',
    options: { A: 'repulsive', B: 'difficult', C: 'interesting', D: 'charming' },
    correctAnswer: 'D',
  },
  {
    id: 34,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Aduma was vociferous during the meeting of the congregation that he succeeded in incurring wrath of the chairman',
    options: { A: 'anger', B: 'admiration', C: 'displeasure', D: 'sympathy' },
    correctAnswer: 'B',
  },
  {
    id: 35,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: It was an inopportune for you to make that suggestion.',
    options: { A: 'ideal', B: 'a wrong', C: 'a exact', D: 'a sad' },
    correctAnswer: 'A',
  },
  {
    id: 36,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: He deviated too much to the peripheral aspects.',
    options: { A: 'unimportant', B: 'superficial', C: 'minor', D: 'main' },
    correctAnswer: 'D',
  },
  {
    id: 37,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: The climate of Nigeria is an enervating one.',
    options: {
      A: 'a weakening',
      B: 'an energy sapping',
      C: 'an invigorating',
      D: 'a sluggish',
    },
    correctAnswer: 'C',
  },
  {
    id: 38,
    subject: 'USE OF ENGLISH',
    question: "Choose the option opposite in meaning to the word underlined: The girl's idiosyncrasy was a passion for bread and butter",
    options: {
      A: 'stupid outburst',
      B: 'general tendency',
      C: 'singular characteristics',
      D: 'occupational calling',
    },
    correctAnswer: 'B',
  },
  {
    id: 39,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Once he has decided that something needs doing, my brother is very unswerving of purpose',
    options: { A: 'erratic', B: 'tenacious', C: 'stubborn', D: 'simple' },
    correctAnswer: 'A',
  },
  {
    id: 40,
    subject: 'USE OF ENGLISH',
    question: 'Choose the option opposite in meaning to the word underlined: Those were the days of the fallacy that some languages are primitive while others are not.',
    options: { A: 'argument', B: 'exercise', C: 'misconception', D: 'truth' },
    correctAnswer: 'D',
  },
  // GENERAL PAPER
  {
    id: 41,
    subject: 'GENERAL PAPER',
    question: 'Sodium chloride may be obtained from brine by',
    options: {
      A: 'Decantation',
      B: 'Distillation',
      C: 'Evaporation',
      D: 'Sublimation',
    },
    correctAnswer: 'C',
  },
  {
    id: 42,
    subject: 'GENERAL PAPER',
    question: 'Which of the following is a chemical compound?',
    options: { A: 'Soap', B: 'Milk', C: 'Urine', D: 'Gold' },
    correctAnswer: 'A',
  },
  {
    id: 43,
    subject: 'GENERAL PAPER',
    question: 'Crystallization is a separation method used',
    options: {
      A: 'where purity of the product is important',
      B: 'where beauty of the product is important',
      C: 'where one of the products is a solid',
      D: 'where the salt cannot be destroyed by heat',
    },
    correctAnswer: 'A',
  },
  {
    id: 44,
    subject: 'GENERAL PAPER',
    question: 'Which of the following is not a mixture?',
    options: {
      A: 'sea water',
      B: 'Iron II sulphide',
      C: 'Petroleum',
      D: 'Urine',
    },
    correctAnswer: 'B',
  },
  {
    id: 45,
    subject: 'GENERAL PAPER',
    question: 'Carbon forms two oxides. Ratio of oxygen in both oxides is 1:2, if one mole of carbon separately combines with oxygen, deduce the formula of the oxides',
    options: { A: 'CO:CO2', B: 'CO2:CO3', C: 'CO2:C2O', D: 'CO2:CO3' },
    correctAnswer: 'A',
  },
  {
    id: 46,
    subject: 'GENERAL PAPER',
    question: 'If 50cm3 of CO2 gas and 50cm3 of SO2 gas are measured, at S.T.P., calculate the amount of each gas in moles (Molar volume = 22.4dm3)',
    options: {
      A: '0.023 mol',
      B: '0.0222 mol',
      C: '0.0002 mol',
      D: '0.0022 mol',
    },
    correctAnswer: 'A',
  },
  {
    id: 47,
    subject: 'GENERAL PAPER',
    question: 'How much volume of ethane would be required to produce 1.12 dm3 of carbon (IV) oxide on combustion in sufficient oxygen? 2C2H6(g)+7O2 -> 4CO2(g) + 6H2O',
    options: {
      A: '56 dm3 of ethane',
      B: '2.24 dm3 of ethane',
      C: '0.56 dm3 of ethane',
      D: '5.6 dm3 of ethane',
    },
    correctAnswer: 'C',
  },
  {
    id: 48,
    subject: 'GENERAL PAPER',
    question: 'By how much would the volume have increased when 10 dm3 of ozone were converted to oxygen 2O3(g) ----> 3O2(g)',
    options: { A: '15dm3', B: '40dm3', C: '0.5 dm3', D: '5 dm3' },
    correctAnswer: 'D',
  },
  {
    id: 49,
    subject: 'GENERAL PAPER',
    question: 'The pressure exerted by a gas is as a result of',
    options: {
      A: 'The continuous random motion of its particles',
      B: 'Bombardment of the walls of the container by its molecules',
      C: 'The collision between the gas molecules',
      D: 'The elastic nature of the gas molecules',
    },
    correctAnswer: 'B',
  },
  {
    id: 50,
    subject: 'GENERAL PAPER',
    question: 'Which of the following gas will diffuse at the slowest rate?',
    options: {
      A: 'Ammonium',
      B: 'Sulphur (IV) oxide',
      C: 'Carbon (II) oxide',
      D: 'Nitrogen',
    },
    correctAnswer: 'B',
  },
  {
    id: 51,
    subject: 'GENERAL PAPER',
    question: 'Element P has an electronic configuration of 2,8,6. Element R has an electronic configuration of 2,8,8,1. What is likely to form if P and R combine?',
    options: {
      A: 'A covalent compound PR',
      B: 'An ionic compound PR2',
      C: 'An ionic compound PR',
      D: 'An ionic compound P2R',
    },
    correctAnswer: 'B',
  },
  {
    id: 52,
    subject: 'GENERAL PAPER',
    question: 'Which is the atomic structure of phosphorus with mass number 31?',
    options: {
      A: 'Protons 15, Neurons 16, Electrons 15',
      B: 'Protons 15, Neurons 16, Electrons 16',
      C: 'Protons 16, Neurons 15, Electrons 15',
      D: 'Protons 16, Neurons 15, Electrons 16',
    },
    correctAnswer: 'A',
  },
  {
    id: 53,
    subject: 'GENERAL PAPER',
    question: 'Which metal has the least tendency to form positive ions?',
    options: { A: 'Iron', B: 'Aluminium', C: 'Sodium', D: 'Calcium' },
    correctAnswer: 'B',
  },
  {
    id: 54,
    subject: 'GENERAL PAPER',
    question: 'What is the number of pairs of shared electrons in a methane molecule?',
    options: { A: '1', B: '2', C: '4', D: '8' },
    correctAnswer: 'C',
  },
  {
    id: 55,
    subject: 'GENERAL PAPER',
    question: 'The percentage by volume of nitrogen in air is high because',
    options: {
      A: 'Nitrogen is relatively inactive',
      B: 'Nitrogen supports life',
      C: 'Nitrogen prevents corrosion of metals',
      D: 'Nitrogen increases the rate of combustion',
    },
    correctAnswer: 'A',
  },
  {
    id: 56,
    subject: 'GENERAL PAPER',
    question: 'Natural water includes the following except',
    options: { A: 'rain water', B: 'spring', C: 'pure water', D: 'lake water' },
    correctAnswer: 'C',
  },
  {
    id: 57,
    subject: 'GENERAL PAPER',
    question: 'Which of the following methods cannot be used to remove permanent hardness in water?',
    options: {
      A: 'addition of washing soda',
      B: 'addition of caustic soda',
      C: 'Permanent method',
      D: 'adding alum to water',
    },
    correctAnswer: 'D',
  },
  {
    id: 58,
    subject: 'GENERAL PAPER',
    question: 'If the solubility of sodium tetraoxosulphate (VI) at 30°C is I8g per l00g. How much is this in gramme per kilogram?',
    options: {
      A: '18kg per l000g',
      B: '180kg per 100g',
      C: '180g per 1000kg',
      D: '180g per kg',
    },
    correctAnswer: 'D',
  },
  {
    id: 59,
    subject: 'GENERAL PAPER',
    question: 'The following are examples of colloid except',
    options: {
      A: 'milk',
      B: 'starch in water',
      C: 'aerosol',
      D: 'ammonium chloride solution',
    },
    correctAnswer: 'D',
  },
  {
    id: 60,
    subject: 'GENERAL PAPER',
    question: 'Oil spillage in ponds and creeks cleaned by',
    options: {
      A: 'Burning off the oil layer',
      B: 'Spraying with detergent',
      C: 'Spraying with common salt',
      D: 'Spraying with hot oil',
    },
    correctAnswer: 'B',
  },
  {
    id: 61,
    subject: 'GENERAL PAPER',
    question: 'The pH of the solutions M, N, O and P are 1, 6, 8 and 10 respectively, therefore',
    options: {
      A: 'None of the solution is acidic',
      B: 'the pH of O is made neutral by water',
      C: 'P is the most acidic solution',
      D: 'M is the most acidic solution',
    },
    correctAnswer: 'D',
  },
  {
    id: 62,
    subject: 'GENERAL PAPER',
    question: 'Which hydroxide dissolves in water to alkaline solution?',
    options: {
      A: 'Aluminium hydroxide',
      B: 'Calcium hydroxide',
      C: 'Copper (II) hydroxide',
      D: 'Iron (III) hydroxide',
    },
    correctAnswer: 'B',
  },
  {
    id: 63,
    subject: 'GENERAL PAPER',
    question: 'Starch molecules can be broken down into smaller molecules by heating in a dilute acid What is this type of reaction called',
    options: { A: 'Cracking', B: 'Hydrolysis', C: 'Oxidation', D: 'Reduction' },
    correctAnswer: 'B',
  },
  {
    id: 64,
    subject: 'GENERAL PAPER',
    question: 'Which of the following cannot be used as an oxidizing agent?',
    options: { A: 'K2Cr2O2', B: 'CO2', C: 'H2S', D: 'HNO3' },
    correctAnswer: 'C',
  },
  {
    id: 65,
    subject: 'GENERAL PAPER',
    question: 'What quantity of copper will be deposited by the same quantity of electricity that deposited 18g of aluminium [Al = 27, Cu= 64]',
    options: { A: '64g', B: '32g', C: '16g', D: '8g' },
    correctAnswer: 'B',
  },
  {
    id: 66,
    subject: 'GENERAL PAPER',
    question: 'Which of the following is not true about semi-conductors?',
    options: {
      A: 'Moving holes are equivalent to moving positive charges',
      B: 'There are two kinds of charge carriers, a free electron and a hole',
      C: 'The escape of a valence electron from atom produces electron-hole par of charge carriers',
      D: 'Increase in temperature increases electrical resistance',
    },
    correctAnswer: 'D',
  },
  {
    id: 67,
    subject: 'GENERAL PAPER',
    question: 'A wire carrying a current of 10A and 2.5m in length is placed in a field of flux intensity 0.14T. What is the force in the wire if it is placed at 60° to the field?',
    options: { A: '30.3N', B: '20.5N', C: '15.3N', D: '10.5N' },
    correctAnswer: 'A',
  },
  {
    id: 68,
    subject: 'GENERAL PAPER',
    question: 'In the transformer, the magnetization of the core is repeatedly reversed by the alternating magnetic field resulting in energy dissipation as heat. This loss is called',
    options: {
      A: 'Eddy currents loss',
      B: 'Hysteresis loss',
      C: 'Flux linkage loss',
      D: 'Joule heat loss',
    },
    correctAnswer: 'B',
  },
  {
    id: 69,
    subject: 'GENERAL PAPER',
    question: 'A step-up transformer is designed to operate from a 25V supply. If the transformer is 80% efficient, determine the current in the primary coil when the output terminals are connected to 240V. 100W lamp',
    options: { A: '5.0A', B: '4.0A', C: '2.5A', D: '2.0A' },
    correctAnswer: 'A',
  },
  {
    id: 70,
    subject: 'GENERAL PAPER',
    question: 'Which of the following pairs consist of fundamental quantities only?',
    options: {
      A: 'Velocity and gravitational potential',
      B: 'Acceleration and field strength',
      C: 'Momentum and work done',
      D: 'Moment and force',
    },
    correctAnswer: 'D',
  },
  {
    id: 71,
    subject: 'GENERAL PAPER',
    question: "One of the limitations of Thompson's model of the atom is that it does not explain,",
    options: {
      A: 'small angle scattering',
      B: 'stability of the atom',
      C: 'ionization progress',
      D: 'the variation of the effective atomic radius',
    },
    correctAnswer: 'B',
  },
  {
    id: 72,
    subject: 'GENERAL PAPER',
    question: 'An atom is said to be excited if an electron of the atom is',
    options: {
      A: 'in the round state',
      B: 'At infinity',
      C: 'promoted to an energy level higher than its original Level',
      D: 'having an energy level of 0.0eV',
    },
    correctAnswer: 'C',
  },
  {
    id: 73,
    subject: 'GENERAL PAPER',
    question: 'The minimum energy necessary to remove an electron from a given atom to infinity is called',
    options: {
      A: 'Excitation energy',
      B: 'Ground state energy',
      C: 'Ionization energy',
      D: 'Binding energy',
    },
    correctAnswer: 'C',
  },
  {
    id: 74,
    subject: 'GENERAL PAPER',
    question: 'Find the dc Broglie wavelength of a 0.01 Kg pellets having a velocity of l0m/s [h = 6.63 x 10-34 Js]',
    options: {
      A: '6.63 x 1031m',
      B: '6.63 x 1032m',
      C: '6.63 x 10-33m',
      D: '6.63 x 1030m',
    },
    correctAnswer: 'C',
  },
];
